server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: changeme

spring:
  security:
    oauth2:
      client:
        registration:
          yahoo:
            client-id: ${YAHOO_CLIENT_ID}
            client-secret: ${YAHOO_CLIENT_SECRET}
            provider: yahoo
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - fspt-r
              - fspt-w
        provider:
          yahoo:
            authorization-uri: https://api.login.yahoo.com/oauth2/request_auth
            token-uri: https://api.login.yahoo.com/oauth2/get_token
            user-info-uri: https://api.login.yahoo.com/openid/v1/userinfo
            user-name-attribute: sub
